apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # L'URL de production de Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    email: patrick.miviere@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik