apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# ... (Partie PVC identique) ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
  namespace: ${NAMESPACE}
  labels:
    app: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
      - name: prestashop
        image: prestashop/prestashop:1.7
        resources:
          requests:
            cpu: "100m"    # 0.1 CPU
            memory: "128Mi"
          limits:
            cpu: "500m"    # 0.5 CPU (Le plafond)
            memory: "512Mi"
        env:
        - name: DB_SERVER
          value: "${APP_NAME}-mariadb"
        - name: DB_USER
          value: "user"
        - name: DB_NAME
          value: "db_data"
        - name: PS_INSTALL_AUTO
          value: "1"
        - name: PS_DOMAIN # forcage du domaine pour eviter la redirection vers ip du pod
          value: "${URL}"
        - name: PS_ENABLE_SSL
          value: "0"
        - name: PS_COUNTRY
          value: "FR"
        - name: PS_LANGUAGE
          value: "fr"
        - name: ADMIN_MAIL
          value: "admin@${APP_NAME}-${NAMESPACE}.com"
        # --- SECRETS DB ---
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: ${APP_NAME}-db-secret
              key: db-password
        # --- SECRET ADMIN ---
        - name: ADMIN_PASSWD
          valueFrom:
            secretKeyRef:
              name: ${APP_NAME}-admin-secret
              key: admin-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: prestashop-storage
          mountPath: /var/www/html
      volumes:
      - name: prestashop-storage
        persistentVolumeClaim:
          claimName: prestashop-pvc
---
# ... (Service identique) ...
apiVersion: v1
kind: Service
metadata:
  name: prestashop-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: prestashop
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME} # Doit matcher le nom du Deployment plus haut
  minReplicas: 1
  maxReplicas: 5    # Jusqu'à 5 copies en cas de tempête !
  targetCPUUtilizationPercentage: 50