apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: prestashop
        image: prestashop/prestashop:1.7
        env:
        - name: DB_SERVER
          value: "${APP_NAME}-mariadb" # Nom du service DB dédié
        - name: DB_USER
          value: "user"
        - name: DB_PASSWD
          value: "password"
        - name: DB_NAME
          value: "prestashop"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: prestashop-storage
          mountPath: /var/www/html
      volumes:
      - name: prestashop-storage
        persistentVolumeClaim:
          claimName: ${APP_NAME}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - port: 80
      targetPort: 80