apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
  namespace: ${NAMESPACE}
  labels:
    app: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
      - name: prestashop
        image: prestashop/prestashop:1.7
        env:
        - name: DB_SERVER
          value: "${APP_NAME}-mariadb"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWD
          value: "password"
        - name: DB_NAME
          value: "db_data"
        - name: PS_INSTALL_AUTO
          value: "1"
        - name: PS_DOMAIN #forçage explicite du domaine pour pas etre redirigé sur l'ip du pod
          value: "${URL}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: prestashop-storage
          mountPath: /var/www/html
      volumes:
      - name: prestashop-storage
        persistentVolumeClaim:
          claimName: prestashop-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prestashop-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: prestashop
  ports:
    - port: 80
      targetPort: 80