apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# ... (Partie PVC identique) ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: ${NAMESPACE}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          requests:
            cpu: "100m"    # 0.1 CPU
            memory: "128Mi"
          limits:
            cpu: "500m"    # 0.5 CPU (Le plafond)
            memory: "512Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: "${APP_NAME}-mariadb"
        - name: WORDPRESS_DB_USER
          value: "user"
        - name: WORDPRESS_DB_NAME
          value: "db_data"
        # --- SECRET ---
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${APP_NAME}-db-secret
              key: db-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
---
# ... (Service identique) ...
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME} # Doit matcher le nom du Deployment plus haut
  minReplicas: 1
  maxReplicas: 5    # Jusqu'à 5 copies en cas de tempête !
  targetCPUUtilizationPercentage: 50