apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # Bitnami écoute sur 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: "${APP_NAME}-mariadb"
        - name: WORDPRESS_DATABASE_USER
          value: "user"
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${CLIENT_NAME}-db-secret
              key: password
        - name: WORDPRESS_DATABASE_NAME
          value: "db_data"
        
        # --- AUTO INSTALLATION ---
        - name: WORDPRESS_USERNAME
          value: "admin"
        - name: WORDPRESS_PASSWORD
          value: "Admin123!" # Mot de passe par défaut
        - name: WORDPRESS_EMAIL
          value: "admin@${URL_SLUG}.${DOMAIN_SUFFIX}"
        - name: WORDPRESS_BLOG_NAME
          value: "Site ${CLIENT_NAME}"
        # ---------------------------------
        
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-storage
          mountPath: /bitnami/wordpress # Dossier standard Bitnami
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: ${APP_NAME}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
  namespace: ${NAMESPACE}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    # Utilise le middleware nommé 'redirect-https' qui est dans le namespace
    traefik.ingress.kubernetes.io/router.middlewares: ${NAMESPACE}-redirect-https@kubernetescrd
spec:
  tls:
  - hosts:
    - ${URL_SLUG}.${DOMAIN_SUFFIX}
    secretName: ${APP_NAME}-tls-secret
  rules:
  - host: ${URL_SLUG}.${DOMAIN_SUFFIX}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${APP_NAME}-service
            port:
              number: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50