version: "3.8"

services:
  nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - wordpress-php

  wordpress-php:
    image: compose-wordpress-php
    build:
      context: ../docker/wordpress-php
    env_file:
      - ../.env

  mysql:
    image: mariadb:10.6
    env_file:
      - ../.env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"  # facultatif sauf pour debug local
    volumes:
      - redis_data:/data

volumes:
  wordpress_data:
  mysql_data:
  redis_data:
