services:
  wp-nginx:
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../docker/nginx/default-wp.conf:/etc/nginx/conf.d/default.conf
      - ../ssl:/etc/nginx/ssl
      - wp_data:/var/www/html

  wp-php:
    env_file:
      - ../.env
    volumes:
      - ../docker/wordpress-php/wp-config.php:/var/www/html/wp-config.php
      - wp_data:/var/www/html

  wp-mariadb:
    env_file:
      - ../.env
    volumes:
      - wp_mariadb_data:/var/lib/mysql
