version: "3.8"

services:
  wp-nginx:
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../ssl:/etc/nginx/ssl
      - wordpress_data:/var/www/html

  wp-php:
    env_file:
      - ../.env
    volumes:
      - ../docker/wordpress-php/wp-config.php:/var/www/html/wp-config.php
      - wordpress_data:/var/www/html

  wp-mysql:
    env_file:
      - ../.env
    volumes:
      - mysql_data:/var/lib/mysql
