services:
  wp-nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - wp-php

  wp-php:
    image: compose-wordpress-php
    build:
      context: ../docker/wordpress-php
    env_file:
      - ../.env

  wp-mariadb:
    image: mariadb:10.6
    env_file:
      - ../.env

  wp-redis:
    image: redis:7
    volumes:
      - wp_redis_data:/data

volumes:
  wp_data:
  wp_mariadb_data:
  wp_redis_data:
