services:
  pts-nginx:
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ../docker/nginx/default-pts.conf:/etc/nginx/conf.d/default.conf
      - ../ssl:/etc/nginx/ssl
      - pts_data:/var/www/html

  pts-php:
    environment:
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
    env_file:
      - ../.env
    volumes:
      - pts_data:/var/www/html

  pts-mariadb:
    env_file:
      - ../.env
    volumes:
      - pts_mariadb_data:/var/lib/mysql

