services:
  pts-php:
    image: compose-prestashop-php
    build:
      context: ../docker/prestashop-php
    env_file:
      - ../.env
    volumes:
      - ../prestashop:/var/www/html

  pts-mariadb:
    image: mariadb:10.6
    env_file:
      - ../.env
    volumes:
      - pts_mysql_data:/var/lib/mysql

  pts-redis:
    image: redis:7
    ports:
      - "6380:6379"  # Port séparé de WP pour debug éventuel
    volumes:
      - pts_redis_data:/data

  pts-nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - pts-php
    volumes:
      - ../prestashop:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d

volumes:
  pts_mysql_data:
  pts_redis_data:
