version: "3.8"

services:
  nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - wordpress-php

  wordpress-php:
    image: compose-wordpress-php
    build:
      context: ../docker/wordpress-php

  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass

volumes:
  wordpress_data:
  mysql_data:
