services:
  wp-nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - wp-php

  wp-php:
    image: compose-wordpress-php
    build:
      context: ../docker/wordpress-php
    env_file:
      - ../.env

  wp-mysql:
    image: mariadb:10.6
    env_file:
      - ../.env

  wp-redis:
    image: redis:7
    ports:
      - "6379:6379"  # facultatif sauf pour debug local
    volumes:
      - redis_data:/data

volumes:
  wordpress_data:
  mysql_data:
  redis_data:
