services:
  pts-nginx:
    image: compose-nginx
    build:
      context: ../docker/nginx
    depends_on:
      - pts-php

  pts-php:
    image: compose-prestashop-php
    build:
      context: ../docker/prestashop-php
    env_file:
      - ../.env

  pts-mariadb:
    image: mariadb:10.6
    env_file:
      - ../.env

  pts-redis:
    image: redis:7
    volumes:
      - pts_redis_data:/data

volumes:
  pts_data:
  pts_mariadb_data:
  pts_redis_data:
